# Generated by Django 4.0.6 on 2024-11-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earmarkedtransaction',
            name='date',
            field=models.CharField(max_length=10),
        ),
    ]
