# Generated by Django 4.0.6 on 2024-11-17 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0002_alter_earmarkedtransaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='earmarkedtransaction',
            name='account_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
