# Generated by Django 4.0.6 on 2024-11-17 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0003_earmarkedtransaction_account_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earmarkedtransaction',
            name='amount',
            field=models.FloatField(),
        ),
    ]
