# Generated by Django 4.0.6 on 2024-11-18 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0006_rename_name_expenseprofile_account_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseprofile',
            name='ust',
            field=models.IntegerField(choices=[(0, '0%'), (19, '19%')], default=19),
        ),
    ]
