# Generated by Django 4.0.6 on 2024-11-27 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0008_remove_parsedtransaction_betrag_netto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parsedtransaction',
            name='gggkto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookkeeping.expenseprofile'),
        ),
    ]
