# Generated by Django 4.0.6 on 2024-11-27 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0010_landlord'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='actual_rent',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='property',
            name='expense_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookkeeping.expenseprofile'),
        ),
        migrations.AddField(
            model_name='property',
            name='landlord',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='bookkeeping.landlord'),
        ),
        migrations.AddField(
            model_name='property',
            name='potential_rent',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=255)),
                ('lease_status', models.CharField(choices=[('empty', 'Empty'), ('renovation', 'Under Renovation'), ('filled', 'Leased')], default='empty', max_length=15)),
                ('rent', models.FloatField(default=0.0)),
                ('maintenance', models.FloatField(default=0.0)),
                ('expense_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookkeeping.expenseprofile')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='bookkeeping.property')),
            ],
        ),
    ]
