# Generated by Django 4.0.6 on 2024-11-27 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0011_property_actual_rent_property_expense_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='expense_profile',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='expense_profile',
        ),
        migrations.AddField(
            model_name='expenseprofile',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_expense_profiles', to='bookkeeping.property'),
        ),
        migrations.AddField(
            model_name='expenseprofile',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit_expense_profiles', to='bookkeeping.unit'),
        ),
    ]
