# Generated by Django 4.0.6 on 2024-12-03 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0012_remove_property_expense_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='actual_rent',
        ),
        migrations.RemoveField(
            model_name='property',
            name='address',
        ),
        migrations.RemoveField(
            model_name='property',
            name='landlord',
        ),
        migrations.AddField(
            model_name='property',
            name='building_no',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='city',
            field=models.CharField(default='0', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='country',
            field=models.CharField(default='Germany', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='landlords',
            field=models.ManyToManyField(related_name='owned_properties', to='bookkeeping.landlord'),
        ),
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial')], default='residential', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='street',
            field=models.CharField(default='Strasse', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='zip',
            field=models.CharField(default=33602, max_length=10),
            preserve_default=False,
        ),
    ]
