# Generated by Django 4.0.6 on 2024-12-03 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0013_remove_property_actual_rent_remove_property_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='lease_status',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='maintenance',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='rent',
        ),
        migrations.AddField(
            model_name='unit',
            name='baths',
            field=models.IntegerField(default=0, help_text='Number of bathrooms in the unit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit',
            name='floor_area',
            field=models.FloatField(default=0, help_text='Floor area in square meters'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit',
            name='market_rent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Market rent for the unit', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit',
            name='rooms',
            field=models.IntegerField(default=0, help_text='Number of rooms in the unit'),
            preserve_default=False,
        ),
    ]
