# Generated by Django 4.0.6 on 2024-12-03 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0014_remove_unit_lease_status_remove_unit_maintenance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='potential_rent',
        ),
    ]
