# Generated by Django 4.0.6 on 2024-12-04 12:39

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0015_remove_property_potential_rent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('ust_type', models.CharField(choices=[('Nicht', 'Nicht'), ('Voll', 'Voll'), ('Teilw', 'Teilw')], default='Voll', max_length=10)),
                ('deposit_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('account_names', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None)),
                ('ibans', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=34), blank=True, default=list, size=None)),
                ('landlords', models.ManyToManyField(related_name='leases', to='bookkeeping.landlord')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='bookkeeping.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='bookkeeping.tenant')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='bookkeeping.unit')),
            ],
        ),
    ]
