# Generated by Django 4.0.6 on 2024-12-04 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0017_remove_expenseprofile_profile_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomeprofile',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
