# Generated by Django 4.0.6 on 2024-12-04 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0018_alter_incomeprofile_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='property',
        ),
    ]
