# Generated by Django 4.0.6 on 2024-12-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0019_remove_tenant_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='rent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
