# Generated by Django 4.0.6 on 2024-12-04 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0020_lease_rent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenseprofile',
            name='property',
        ),
        migrations.RemoveField(
            model_name='expenseprofile',
            name='unit',
        ),
        migrations.AddField(
            model_name='expenseprofile',
            name='profile_name',
            field=models.CharField(default='profile', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incomeprofile',
            name='account_name',
            field=models.CharField(default='acount name', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incomeprofile',
            name='profile_name',
            field=models.CharField(default='profile name', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expenseprofile',
            name='lease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_profiles', to='bookkeeping.lease'),
        ),
    ]
