# Generated by Django 4.0.6 on 2024-12-04 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0021_remove_expenseprofile_property_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseprofile',
            name='booking_no',
            field=models.CharField(default=0, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incomeprofile',
            name='booking_no',
            field=models.CharField(default=0, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incomeprofile',
            name='ust',
            field=models.IntegerField(choices=[(0, '0%'), (7, '7%'), (19, '19%')], default=19),
        ),
        migrations.AlterField(
            model_name='expenseprofile',
            name='lease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_profiles', to='bookkeeping.lease'),
        ),
        migrations.AlterField(
            model_name='incomeprofile',
            name='lease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='income_profiles', to='bookkeeping.lease'),
        ),
    ]
