# Generated by Django 4.0.6 on 2024-12-05 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0022_expenseprofile_booking_no_incomeprofile_booking_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parsedtransaction',
            name='gggkto',
        ),
        migrations.AddField(
            model_name='parsedtransaction',
            name='booking_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='parsedtransaction',
            name='property_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='parsedtransaction',
            name='transaction_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='parsedtransaction',
            name='unit_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='parsedtransaction',
            name='ust_type',
            field=models.IntegerField(choices=[(0, '0%'), (7, '7%'), (19, '19%')], default=19),
        ),
        migrations.AlterField(
            model_name='expenseprofile',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='expenseprofile',
            name='transaction_type',
            field=models.CharField(choices=[('bk_back_payments', 'BK Back Payments'), ('bk_general_electricity', 'BK General Electricity'), ('bk_insurance', 'BK Insurance'), ('bk_heating_costs', 'BK Heating Costs'), ('other_non_bk', 'Other Non-BK'), ('bk_elevator_system', 'BK Elevator System'), ('maintenance_direct', 'Maintenance Direct'), ('bk_water', 'BK Water'), ('bk_drainage', 'BK Drainage'), ('bk_caretaker_cleaning', 'BK Caretaker / Cleaning'), ('bk_property_taxes', 'BK Property Taxes'), ('bk_waste_disposal', 'BK Waste Disposal'), ('bk_heating_costs_ista', 'BK Heating Costs per ISTA'), ('interest', 'Interest'), ('maintenance_activation', 'Maintenance Activation'), ('bk_direct', 'BK Direct'), ('bk_miscellaneous', 'BK Miscellaneous'), ('investment_rent', 'Investment Rent'), ('deposit_withdrawal', 'Deposit / Withdrawal')], default='other_non_bk', max_length=50),
        ),
        migrations.AlterField(
            model_name='incomeprofile',
            name='transaction_type',
            field=models.CharField(choices=[('rent', 'Rent'), ('bk_advance_payments', 'BK Advance Payments'), ('security_deposit', 'Security Deposit'), ('subsidy', 'Subsidy'), ('deposit_withdrawal', 'Deposit / Withdrawal')], default='rent', max_length=30),
        ),
    ]
