# Generated by Django 4.0.6 on 2024-12-15 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0023_remove_parsedtransaction_gggkto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseprofile',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_profiles', to='bookkeeping.property'),
        ),
        migrations.AddField(
            model_name='incomeprofile',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='income_profiles', to='bookkeeping.property'),
        ),
    ]
