# Generated by Django 4.0.6 on 2024-12-16 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0024_expenseprofile_property_incomeprofile_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='ust_type',
            field=models.CharField(choices=[('Nicht', '0'), ('Voll', '19'), ('Teilw', '7')], default='Voll', max_length=10),
        ),
    ]
