# Generated by Django 4.0.6 on 2024-12-17 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0025_alter_lease_ust_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseprofile',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incomeprofile',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
