# Generated by Django 4.0.6 on 2024-12-17 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0027_remove_landlord_contact_info_landlord_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
