# Generated by Django 4.0.6 on 2024-12-19 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0031_parsedtransaction_related_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload a property image', null=True, upload_to='property_images/'),
        ),
    ]
