# Generated by Django 4.0.6 on 2024-12-19 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0032_property_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.ImageField(blank=True, default='property_images/default_image.png', help_text='Upload a property image', null=True, upload_to='property_images/'),
        ),
    ]
