# Generated by Django 4.0.6 on 2025-01-06 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0033_alter_property_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parsedtransaction',
            name='related_property',
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('Residential', 'Residential'), ('Commercial', 'Commercial')], default='residential', max_length=20),
        ),
    ]
