# Generated by Django 4.0.6 on 2025-01-06 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0034_remove_parsedtransaction_related_property_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parsedtransaction',
            name='property_name',
        ),
        migrations.AddField(
            model_name='parsedtransaction',
            name='related_property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookkeeping.property'),
        ),
    ]
