# Generated by Django 4.0.6 on 2025-01-07 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0035_remove_parsedtransaction_property_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='ust_type',
            field=models.CharField(choices=[('Nicht', '0'), ('Voll', '19'), ('Teilw', '7')], default='Voll', max_length=10),
        ),
    ]
