# Generated by Django 4.0.6 on 2025-01-07 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0036_property_ust_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseprofile',
            name='booking_no',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='incomeprofile',
            name='booking_no',
            field=models.CharField(max_length=100),
        ),
    ]
