# Generated by Django 5.1.5 on 2025-02-18 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0040_alter_property_image_alter_property_property_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='ust_type',
        ),
    ]
