# Generated by Django 5.1.5 on 2025-02-19 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0041_remove_property_ust_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='iban',
            field=models.CharField(blank=True, max_length=34, null=True, unique=True),
        ),
    ]
