# Generated by Django 5.1.5 on 2025-02-19 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0042_property_iban'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='iban',
        ),
    ]
