# Generated by Django 5.1.5 on 2025-03-05 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0043_remove_property_iban'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='partial_tax_rate',
            field=models.FloatField(blank=True, max_length=5, null=True),
        ),
    ]
