# Generated by Django 5.1.5 on 2025-03-05 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0044_property_partial_tax_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='baths',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='market_rent',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='rooms',
        ),
        migrations.AddField(
            model_name='unit',
            name='additional_costs',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Additional costs', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='floor',
            field=models.IntegerField(blank=True, help_text='Floor number of the unit', null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='position',
            field=models.CharField(blank=True, choices=[('Left', 'Left'), ('Middle', 'Middle'), ('Right', 'Right')], default='Middle', help_text='Unit position (Left, Middle, Right)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='rent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Rent for the unit', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='floor_area',
            field=models.FloatField(blank=True, help_text='Floor area in square meters', null=True),
        ),
    ]
