# Generated by Django 5.1.5 on 2025-03-05 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0045_remove_unit_baths_remove_unit_market_rent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lease',
            name='tenant',
        ),
        migrations.AddField(
            model_name='lease',
            name='tenants',
            field=models.ManyToManyField(related_name='leases', to='bookkeeping.tenant'),
        ),
    ]
