# Generated by Django 5.1.5 on 2025-03-06 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0046_remove_lease_tenant_lease_tenants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landlord',
            old_name='company_name',
            new_name='object',
        ),
    ]
