# Generated by Django 5.1.5 on 2025-03-06 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0047_rename_company_name_landlord_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='ust_type',
            field=models.CharField(choices=[('Ohne', '0'), ('Mit', '19')], default='Ohne', max_length=10),
        ),
    ]
