# Generated by Django 5.1.5 on 2025-03-18 14:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0048_alter_lease_ust_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='auto_calculate_tax',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='tax_calculation_method',
            field=models.CharField(blank=True, choices=[('none', 'Manually Entered'), ('sq_meterage', 'Based on Sq Meterage'), ('income', 'Based on Income')], default='none', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='partial_tax_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=5, null=True),
        ),
    ]
