# Generated by Django 5.1.5 on 2025-03-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0049_property_auto_calculate_tax_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='additional_costs',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Additional costs for the lease', max_digits=10, null=True),
        ),
    ]
