# Generated by Django 5.1.5 on 2025-04-10 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0051_property_locked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='earmarkedtransaction',
            name='booking_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
