# Generated by Django 5.1.5 on 2025-04-10 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0052_earmarkedtransaction_booking_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenseprofile',
            name='booking_no',
        ),
        migrations.RemoveField(
            model_name='incomeprofile',
            name='booking_no',
        ),
    ]
