# Generated by Django 5.1.5 on 2025-04-11 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0053_remove_expenseprofile_booking_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='earmarkedtransaction',
            name='flagged_for_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='earmarkedtransaction',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='earmarkedtransaction',
            name='review_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earmarkedtransaction',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
