# Generated by Django 5.1.5 on 2025-04-11 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0054_earmarkedtransaction_flagged_for_review_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='earmarkedtransaction',
            name='reviewed',
        ),
        migrations.AddField(
            model_name='incomeprofile',
            name='split_details',
            field=models.JSONField(blank=True, help_text="Optional: define exact split for this profile, e.g. {'rent': 1500, 'bk_advance_payments': 250, 'security_deposit': 250}", null=True),
        ),
    ]
