# Generated by Django 5.1.5 on 2025-04-11 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0055_remove_earmarkedtransaction_reviewed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomeprofile',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('rent', 'Rent'), ('bk_advance_payments', 'BK Advance Payments'), ('security_deposit', 'Security Deposit'), ('subsidy', 'Subsidy'), ('deposit_withdrawal', 'Deposit / Withdrawal')], default='rent', max_length=30, null=True),
        ),
    ]
