# Generated by Django 5.1.5 on 2025-04-11 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0056_alter_incomeprofile_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
