# Generated by Django 5.1.5 on 2025-04-14 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0057_tenant_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseprofile',
            name='invoice',
            field=models.URLField(blank=True, null=True),
        ),
    ]
