# Generated by Django 5.1.5 on 2025-05-06 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0058_alter_expenseprofile_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parsedtransaction',
            name='invoice',
            field=models.URLField(blank=True, null=True),
        ),
    ]
