# Generated by Django 5.1.5 on 2025-05-08 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0059_alter_parsedtransaction_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='position',
        ),
        migrations.AddField(
            model_name='unit',
            name='investition_miete',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Investment rent', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='stellplatz_miete',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Parking space rent', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='expenseprofile',
            name='frequency',
            field=models.CharField(blank=True, choices=[('monthly', 'Monatlich'), ('bimonthly', 'Zweimonatlich'), ('quarterly', 'Vierteljährlich'), ('yearly', 'Jährlich')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='incomeprofile',
            name='frequency',
            field=models.CharField(blank=True, choices=[('monthly', 'Monatlich'), ('bimonthly', 'Zweimonatlich'), ('quarterly', 'Vierteljährlich'), ('yearly', 'Jährlich')], max_length=12, null=True),
        ),
    ]
