# Generated by Django 5.1.5 on 2025-05-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0060_remove_unit_position_unit_investition_miete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='guarantee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
