# Generated by Django 5.1.5 on 2025-05-08 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0061_lease_guarantee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incomeprofile',
            name='lease',
        ),
        migrations.AddField(
            model_name='incomeprofile',
            name='leases',
            field=models.ManyToManyField(blank=True, related_name='income_profiles', to='bookkeeping.lease'),
        ),
    ]
